### PR TITLE
Fixed #385 Broken "Delete a pipeline" Button

### LINKED ISSUE #385: Broken Button "Delete a Pipeline" in the Analysis Catalog Page
**Steps to Reproduce**

This Bug is Present in the Pipelines section of the "Analysis Catalog" page ,
**You will need have pipelines uploaded to see this bug , If you are running minChris as a backend then you'll not see anything in the Pipelines section , because miniChris doesnot has pipelines preuploaded , to upload pipelines refer this --** https://github.com/FNNDSC/caw#testing

After you have your pipelines uploaded go to the "Pipelines" section of "Analysis Catalog" page and **select any  pipeline** , **you'll see a delete pipeline button** , **now on reducing the width of the screen the button will break** , **also you can use chrome Devtools to open the mobile version of the website to see this bug.** I am attaching the screenshots of both take a look.

bug analysis catalog page

### PR DESCRIPTION
**Pull request by Prakashh21**
This fixes #385 

Increase the width of the button slightly and added minWidth.
I have added screenshots below take a look.

button fixed

### CODE REVIEW

File: src/components/catalog/DisplayPage.tsx [hunk 1]
```diff
@@ -335,7 +335,8 @@ const DisplayPage = ({
             {showPipelineButton && (
               <Button
                 style={{
-                  width: "45%",
+                  width: "55%",
```
Comment (jennydaman) [inline src/components/catalog/DisplayPage.tsx:338]: This is a large and dynamic component, so setting width based on some percentage of its parent's size could be a brittle solution.

I think it makes more sense here to have the minimum width be dependent on the size of its contents instead of the size of the parent.

Comment (Prakashh21) [reply src/components/catalog/DisplayPage.tsx]: Alright @jennydaman width:fit-content would do it.. Thanks !! for the feedback .. I have pushed the changes.

Comment (jennydaman) [reply src/components/catalog/DisplayPage.tsx]: It always seems like CSS has these features that you gotta dig around for.
